    ::: {.trmenv #M17E title="(M1,7)E" latex="{(M1,7)\textsubscript{E}}"}
    For each embedding $\sigma$ of $E$ into $\CC$, a vector space $M_\sigma$ over $\QQ$, the Betti realisation with respect to $\sigma$, and an involutive system of isomorphisms $F_\infty\colon M_\sigma\simto M_{\bar{\sigma}}$.
    :::

    We have $N_\BB=\bigoplus M_\sigma$, with the evident structure of a module over $A_\BB=\QQ^{\Hom(E,\CC)}$, and $F_\infty$ is the sum of the $F_\infty$.
    As in \ref{minus-three-points-chunk-1.14}, we have a variant:

    ::: {.trmenv #Mp1E title="(M'1)E" latex="{(M'1)\textsubscript{E}}"}
    For each embedding of $E$ into an algebraic closure $C$ of $\RR$, a vector space $M_\sigma$ over $\QQ$, functorial in $C$.
    :::

    ::: {.trmenv #Mp2E title="(M'2)E" latex="{(M'2)\textsubscript{E}}"}
    An $E$-vector space $M_\DR$.
    :::

    ::: {.trmenv #Mp8E title="(M'8)E" latex="{(M'8)\textsubscript{E}}"}
    A filtration $F$ of $M_\DR$, the Hodge filtration.
    :::

    We have $N_\DR=M_\DR$, with the structure of an $A_\DR$-module given by that of the vector space over $E$.

    ::: {.trmenv #Mp3E title="(M'3)E" latex="{(M'3)\textsubscript{E}}"}
    (cf. [(M3)](minus-three-points-m3), [(M9)](minus-three-points-m9)) An $\AAf$-sheaf $M_\AAf$ on $\Spec(E)$ (cf. \ref{minus-three-points-chunk-1.14}).
    :::

    We define $N_\AAf$ as its direct image over $\Spec(\QQ)$: $N_\AAf(\bar{\QQ})$ is the sum over the $\sigma\colon E\to\bar{\QQ}$ of the $M_AAf(\bar{\QQ})$.

    ::: {.trmenv #Mp4E title="(M'4)E" latex="{(M'4)\textsubscript{E}}"}
    For each place $v$ of $E$ over $p\not\in P$, a vector space $M_\crisv$ over the completion $E_v$ of $E$ at $v$.
    Let $F_v^*$ be the automorphism of $E_v$ that induces $x\mapsto x^p$ on the residue field.
    We give an $F_v^*$-linear $\phi_v\colon M_\crisv\mapsto M_\crisv$.
    :::

    \oldpage{102}We have $E\otimes\QQ_p=\bigoplus_{v\mid p}E_v$, and $N_\crisp$ is the sum of the $M_\crisv$.

    ::: {.trmenv #Mp5E title="(M'5)E" latex="{(M'5)\textsubscript{E}}"}
    Comparison isomorphisms
    $$
      \begin{aligned}
        \comp_{\DR,\sigma}\colon M_\sigma(C)\otimes C
        &\simto M_\DR\otimes_{E,\sigma}C
      \\\comp_{\AAf,\sigma}\colon M_{\sigma}\otimes\AAf
        &\simto M_\AAf(\bar{E}_C)
      \end{aligned}
    $$
    both functorial in $C$ (where $\bar{E}_C$ is the algebraic closure of $E$ in $C$, with respect to $\sigma$), as well as
    $$
      \comp_{\crisv,\DR}\colon M_\DR\otimes_E E_v \simto M_\crisv.
    $$
    :::

    By summing over $\sigma$ (resp. $v$), these give [(M'5)](minus-three-points-mp5).

    ::: {.trmenv #Mp6E title="(M'6)E" latex="{(M'6)\textsubscript{E}}"}
    A filtration $W$ of the objects [(M'1)E](#Mp1E), [(M'2)E](#Mp2E), [(M'3)E](#Mp3E), and [(M'4)E](#Mp4E), respected by the comparison isomorphisms.
    :::

    We leave to the reader the task of translating axioms [(AM1)](minus-three-points-am1), [(AM3)](minus-three-points-am3), and [(AM4)](minus-three-points-am4), which remain to be imposed, into this language (cf. \ref{minus-three-points-chunk-1.14}).
::::

::: {.rmenv #chunk-1.19 title="1.19" latex="{1.19}"}
    With the definition \ref{minus-three-points-1.17} of smooth realisation systems over $S=\Spec(\OO)$, the functor given by forgetting the $A$-module structure, which takes values in smooth realisation systems over $\Spec(\ZZ)\setminus P$, is called the "*direct image of $S$ in $\Spec(\ZZ)\setminus P$*".
    In the various realisations of [(1.18)](#chunk-1.18), it corresponds to the direct image.
    Its left adjoint, $M\mapsto A\otimes M$ (cf. \fref{minus-three-points-5.3}), is the *inverse image*.
:::

::: {.rmenv #chunk-1.20 title="1.20" latex="{1.20}"}
    If $S$ is an open of the spectrum of the ring of integers of a finite extension $E$ of $\QQ$, then we can modify the description in [(1.18)](#chunk-1.18) as follows to define smooth realisation systems over $S$.

    - In [(AM3)](minus-three-points-am3), we ask for each $\QQ_\ell$-sheaf $M_\ell$ induced by $M_\AAf$ to come from a smooth $\QQ_\ell$-sheaf on $S[1/\ell]$.
    - In [(M'4)E](#Mp4E), for each residue field $k(v)$ of $S$, we ask for $M_\crisv$ over the field of fractions $K_v$ of Witt vectors over $k(v)$, endowed with a semi-linear $\phi_v$.
      The crystalline comparison isomorphism of [(M'5)E](#Mp5E) then becomes
      $$
        M_\DR\otimes E_v \simto M_\crisv\otimes_{K_v}E_v.
      $$
:::

:::: {.rmenv #chunk-1.21 title="1.21" latex="{1.21}"}
    Let $S$ be smooth over $\Spec(\ZZ)$.
    Here is a provisional definition of smooth realisation systems over $S$, inspired by [(1.18)](#chunk-1.18).
    The data is as follows:

    ::: {.trmenv #Mp1S title="(M'1)S" latex="{(M'1)\textsubscript{S}}"}
    For $C$ an algebraic closure of $\RR$, a locally constant sheaf $M_\BB(C)$ of $\QQ$-vector spaces on $S(C)$, functorial in $C$.
    We set $M_\BB\coloneqq M_\BB(\CC)$.
    :::

    ::: {.trmenv #Mp2S title="(M'2)S" latex="{(M'2)\textsubscript{S}}"}
    \oldpage{103}A vector bundle $M_\DR$ with integrable connection on $S_\QQ$, assumed to be regularly singular at infinity.
    :::

    ::: {.trmenv #Mp8S title="(M'8)S" latex="{(M'8)\textsubscript{S}}"}
    A filtration $F$ of $M_\DR$ by vector subbundles: the Hodge filtration.
    We assume "transversality":
    $$
      \nabla F^p \subset \Omega^1\otimes F^{p-1}.
    $$
    :::

    ::: {.trmenv #Mp3S title="(M'3)S" latex="{(M'3)\textsubscript{S}}"}
    A smooth $\AAf$-sheaf $M_\AAf$ on $S_\QQ$.
    :::

    ::: {.trmenv #Mp4S title="(M'4)S" latex="{(M'4)\textsubscript{S}}"}
    For every prime number $p$, an $F$-isocrystal $M_\crisp$ on the reduction $S_p$ of $S$ $\mod p$.
    :::

    ::: {.trmenv #Mp5S title="(M'5)S" latex="{(M'5)\textsubscript{S}}"}
    Comparison isomorphisms
    $$
      \begin{aligned}
        \comp_{\DR,\BB}\colon
        &M_\BB(C)\otimes C \simto (M_\DR\otimes C)^\nabla
      \\\comp_{\AAf,\BB}\colon
        &M_\BB^{(C)}\otimes\AAf \to \text{inverse image of }M_\AAf\text{ on }S(C)
      \end{aligned}
    $$
    that are functorial in $C$, where we denote by $M_\DR\otimes C$ the inverse image of $M_\DR$ on $S_C$, and by $(-)\nabla$ the sheaf of its horizontal sections on $S(C)$.
    Instead of giving $M_\AAf$ in [(M'3)S](#Mp3S), we can only give the $\QQ_\ell$ sheaves $M_\ell$ that are deduced from it, along with the comparison isomorphisms $\comp_{\ell,\BB}$ from $M_\BB\otimes\QQ_\ell$ to the inverse image of $M_\ell$, and impose the existence of a lattice $L$ in $M_\BB(C)$ such that $L\otimes\ZZ_\ell$ corresponds to a $\ZZ_\ell$-sheaf $L_\ell$ with $L_\ell\otimes\QQ_\ell\simto M_\ell$, cf. \ref{minus-three-points-chunk-1.14}.

    As for $\comp_{\crisp,\DR}$, let $S_{(p)}^\an$ be the rigid analytic space that is the general fibre of the formal scheme over $\ZZ_p$ given by the formal completion of $S$ along $S_p$;
    we want an isomorphism between bundles with connection on $S_{(p)}^\an$ induced by $M_\DR$ and $M_\crisp$.
    :::

    ::: {.trmenv #Mp6S title="(M'6)S" latex="{(M'6)\textsubscript{S}}"}
    A filtration $W$ of the objects [(M'1)S](#Mp1S) to [(M'4)S](#Mp4S), respected by the comparison isomorphisms.
    :::

    The axioms are modified as follows.
    In [(AM1)](minus-three-points-am1), we want a variation of mixed Hodge structures;
    [(AM3)](minus-three-points-am3) becomes: $M_\ell$ comes from a smooth $\QQ_\ell$-sheaf on $S[1/\ell]$;
    for [(AM4)](minus-three-points-am4), a condition is imposed for every closed point of $S$.

    As a catch-all, this category does the job (cf. [(1.13)](#chunk-1.13) nonetheless).
    Additional axioms will always be natural, notably concerning the behaviour at infinity of the variation of mixed Hodge structures $H_\BB$ (cf. [@SZ]).
::::

::: {.rmenv #chunk-1.22 title="1.22 Definition" latex="{1.22 Definition}"}
    \oldpage{104}
    Let $E$ be a finite extension of $\QQ$.
    Then a realisation system *with coefficients in $E$* is a realisation system $M$ endowed with the structure of an $E$-modules, $E\to\End(M)$.
:::

Up until now, our motives have been "isomotives": the $\Hom$ are vector spaces over $\QQ$.
For motives with integer coefficients, I propose the following definitions.

::: {.rmenv #chunk-1.23 title="1.23 Definition" latex="{1.23 Definition}"}
    A realisation system $M$ over $\QQ$ (resp. $\Spec\ZZ\setminus P$) *with integer coefficients* is a realisation system, denoted by $M\otimes\QQ$, endowed with a lattice $M_\BB\subset(M\otimes\QQ)_\BB$ such that, for all $\ell$, $M_\ell\coloneqq M_\BB\otimes\ZZ_\ell\subset(M\otimes\QQ)_\ell$ is stable under $\Gal(\bar{\QQ}/\QQ)$.
:::

:::: {.rmenv #chunk-1.24 title="1.24" latex="{1.24}"}
    On a more general base $S$, a realisation system *with integer coefficients* is a realisation system $M\otimes\QQ$ endowed with a local system of torsion-free $\ZZ$-modules $M_\BB\subset(M\otimes\QQ)_\BB$ satisfying $M_\BB\otimes\QQ\simto(M\otimes\QQ)_\BB$ (a "lattice") and such that the $\ZZ_\ell$-sheaf $M_\BB\otimes\ZZ_\ell$ on $S(\CC)$ corresponds, under $\comp_{\ell,\BB}$, to a smooth $\ZZ_\ell$-sheaf $M_\ell\subset(M\otimes\QQ)_\ell$ on $S[1/\ell]$.

    This causes us to modify [(M'1)S](#Mp1S), [(M'3)S](#Mp3S), and [(M'5)S](#Mp5S) as follows.

    ::: {.trmenv #Mp1SZ title="(M'1)SZ" latex="{(M'1)\textsubscript{SZ}}"}
    $M_\BB(C)$ is a local system of free $\ZZ$-modules.
    :::

    ::: {.trmenv #Mp3SZ title="(M'3)SZ" latex="{(M'3)\textsubscript{SZ}}"}
    The data of a $\ZZ_\ell$-sheaf $M_\ell$ on $S[1/\ell]$.
    :::

    ::: {.trmenv #Mp5SZ title="(M'5)SZ" latex="{(M'5)\textsubscript{SZ}}"}
    Replace $\comp_{\AAf,\BB}$ by isomorphisms $\comp_{\ell,\BB}$ from $M_\BB\otimes\ZZ_\ell$ to the inverse image of $M_\ell$ on $S(C)$.
    :::
::::

::: {.rmenv #chunk-1.25 title="1.25" latex="{1.25}"}
    In [(1.24)](#chunk-1.24), the data of the $M_\ell$ is equivalent to that of a projective system of sheaves of $\ZZ/(n)$-modules on the $S[1/n]$:
    $$
      M_{\ZZ/(n)}\colon \prod_{\ell\mid n}M_\ell/n M_\ell
    $$
    and the data of the comparison morphisms is equivalent to that of an isomorphism of projective systems from $\comp_{\AA/n,\BB}\colon M_\BB\otimes\ZZ/(n)$ to the inverse image of $M_{\ZZ/(n)}$ on $S(C)$.

    In the setting of [(1.23)](#chunk-1.23), we can prefer to think of the $M_{\ZZ/(n)}$ as representations of $\Gal(\bar{\QQ}/\QQ)$.
    We again set $M_{\hZZ}=\limproj M_{\ZZ/(n)}=\prod M_\ell$.
:::

::: {.rmenv #chunk-1.26 title="1.26" latex="{1.26}"}
    Combining the variants in [(1.22)](#chunk-1.22) and [(1.24)](#chunk-1.24), we similarly define motives over $S$ with coefficients in the ring of integers of a finite extension of $\QQ$.
:::



# Examples {#section-2}

::: {.rmenv #chunk-2.1 title="2.1" latex="{2.1}"}
\oldpage{105}The *Tate motive* $\ZZ(1)$ is a motive over $\Spec(\ZZ)$ \ref{minus-three-points-1.15} with integer coefficients [(1.23)](#chunk-1.23).
Here is its description as a realisation system, in the language of \ref{minus-three-points-1.9} and \ref{minus-three-points-chunk-1.14} (along with [(1.25)](#chunk-1.25)):

- [(M1)](minus-three-points-m1) and [(M7)](minus-three-points-m7): $\ZZ(1)_\BB=2\pi i\ZZ\subset\CC$ and $F_\infty=-1$.
- [(M'1)](minus-three-points-mp1): $\ZZ(1)_\BB(C)=2\pi i\ZZ\subset C$.
- [(M2)](minus-three-points-m2) and [(M'2)](minus-three-points-mp2): $\ZZ(1)_\DR=\QQ(1)_\DR=\QQ$.
- [(M3)](minus-three-points-m3) and [(M9)](minus-three-points-m9): $\ZZ(1)_{\ZZ/n}$ is the group $\mu_n\subset\CC^\times$ of $n$-th roots of unity.
  The transition morphisms are the $\mu_n\to\mu_m\colon x\mapsto x^{n/m}$ for $m\mid n$.
  The action of $\Gal(\bar{\QQ}/\QQ)$ is its action on the $\mu_n$.
  In the variant [(M'3)](minus-three-points-mp3), we have $\ZZ(1)_{\ZZ/n}(\bar{k})=\mu_n(\bar{k})$.

  We thus have that $\ZZ(1)_\ell=\limproj\mu_{\ell^n}(\CC)$.
- [(M4)](minus-three-points-m4), [(M10)](minus-three-points-m10), and [(M'4)](minus-three-points-mp4): $\ZZ(1)_\crisp=\QQ_p$ and $\phi_p=1/p$.
- [(M5)](minus-three-points-m5): The canonical comparison isomorphism $\comp_{\DR,\BB}$ is induced by the inclusions $\ZZ(1)_\BB=2\pi i\ZZ\subset\CC$ and $\ZZ(1)_\DR=\QQ\subset\CC$, i.e.
  $$
    \ZZ(1)_\BB\otimes\CC \simto \CC \simfrom \ZZ(1)_\DR\otimes\CC.
  $$
  The isomorphism $\comp_{\ZZ/n,\BB}$ [(1.25)](#chunk-1.25) is induced by
  $$
    \exp(x/n)\colon \ZZ(1)_\BB \to \ZZ/n(1)\subset\CC^\times.
  $$
  The isomorphism $\comp_{\crisp,\DR}$ is induced by the inclusion $\QQ\subset\QQ_p$.
- [(M'5)](minus-three-points-mp5): Replace $\CC$ by $C$ in [(M5)](minus-three-points-m5).
- [(M6)](minus-three-points-m6) and [(M8)](minus-three-points-m8): $\ZZ(1)$ is of pure weight $-2$, and $\ZZ(1)_\DR$ is of pure Hodge filtration $-1$: the Hodge type is $(-1,-1)$.
:::

::: {.rmenv title="Notation" latex="{Notation}"}
$\ZZ(n)\coloneqq\ZZ(1)^{\otimes n}$, $\QQ(n)\coloneqq\ZZ(n)\otimes\QQ$, and, for any motive $M$, $M(n)\coloneqq M\otimes\ZZ(n)$.
Depending on the context, we also denote by $(n)$ taking the tensor product with a realisation of $\ZZ(n)$.

If $X$ is smooth and projective over $k$, and absolutely irreducible of dimension $n$, then $\HH_\mot^{2n}(X)$ is the motive over $k$ induced from $\QQ(-n)$ by change of base from $\QQ$ to $k$.
:::

::: {.rmenv #chunk-2.2 title="2.2" latex="{2.2}"}
For an abelian variety $A$ over $\QQ$, we denote by $T(A)\otimes\QQ$ the motive $\HH_1^\mot(A)$ that is dual to $\HH_\mot^1(A)$, and by $T(A)$ the motive with integer coefficients defined by the integer structure $\HH_1(A(\CC),\ZZ)\subset\HH_1(A(\CC),\QQ)=(T(A)\otimes\QQ)_\BB$.
\oldpage{106}The functor $A\mapsto T(A)$ is fully faithful: from $T(A)$ we can recover $\Lie(A)=T(A)_\DR/F^0$ and the complex torus
$$
  A(\CC)
  = T(A)_\BB\setminus\Lie(A)
  = T(A)_\BB\setminus T(A)_\DR\otimes\CC/F^0.
$$
The complex torus $A(\CC)$ determines the abelian variety $A_\CC$ over $\CC$ induced by $A$, and the $\QQ$-structure is uniquely determined by that of the Lie algebra.

An abelian scheme $A$ over $S$ similarly defines a smooth motive with integer coefficients $T(A)$ over $S$.
:::

::: {.rmenv #chunk-2.3 title="2.3" latex="{2.3}"}
Recall that a *smooth $1$-motive* $X$ over a scheme $S$ consists of

a. a group scheme $L$ over $S$ that, locally, for the étale topology, is a constant group scheme defined by a free $\ZZ$-module of finite type;
  an abelian scheme $A$ over $S$, and a torus $T$ over $S$;
b. an extension $E$ of $A$ by $T$, and a morphism $\bar{u}\colon L\to A$;
c. a morphism $u\colon L\to E$ lifting $\bar{u}$.

We write $X=[L\xrightarrow{u}E]$.

A $1$-motive $X$ over $\QQ$ defines a motive over $\QQ$ with integer coefficients $T(X)$ (cf. [@D3, Section 10, but the crystalline aspect is missing]), and the functor $X\mapsto T(X)$ is fully faithful (cf. [@D3, both 10.1.3 and 2.2]).

For $X=[\ZZ\to0]$, $T(X)$ is the unit motive $\ZZ(0)$.
For $X=[0\to\Gm]$, $T(X)$ is the Tate motive $\ZZ(1)$.
For an abelian variety $A$ and $X=[0\to A]$, $T(X)=T(A)$.
Of course, here, as in [(2.2)](#chunk-2.2), we can take more general bases than $\Spec(\QQ)$.
:::

::: {.rmenv #chunk-2.4 title="2.4" latex="{2.4}"}
I conjecture that the set of motives with integer coefficients of the form $T(X)$ for some $1$-motive $X$ is stable under extensions.
If $T'$ is a motive with integer coefficients, with $T'\otimes\QQ\simto T(X)\otimes\QQ$, then $T'$ is of the form $T(X')$ with $X'$ isogenous to $X$.
The conjecture is thus equivalent to the claim that the set of motives $T(X)\otimes\QQ$, for $1$-motives $X$, is stable under extensions.
The word "conjecture" is an abuse of terminology, since the statement itself is not precise.
What is conjectured is that every realisation system \ref{minus-three-points-1.9} (or [(1.24)](#chunk-1.24), over $S$) that is an extension $T(X)$ by $T(Y)$ (for $1$-motives $X$ and $Y$), and "natural", "coming from geometry", is isomorphic to that defined by a $1$-motive $Z$ that is an extension of $X$ by $Y$.

\oldpage{107}A point $a$ of an abelian variety $A$ over $\QQ$ defines a $1$-motive $[\ZZ\xrightarrow{u}A]$ with $u(1)=a$.
The motive $T([\ZZ\xrightarrow{u}A])$ is an extension of $\ZZ(0)$ by $T(A)$, and the conjecture, applied to $\ZZ(0)$ and $T(A)$, implies that
$$
  A(\QQ) \simto \Ext^1(\ZZ(0),T(A))
$$
or, equivalently,
$$
  A(\QQ)\otimes\QQ \simto \Ext^1(\QQ(0),T(A)\otimes\QQ)
$$
(where $\Ext^1$ is in the abelian category of motives).

More generally, if $E$ is an extension of an abelian variety by a torus, we want
$$
  E(\QQ) \simto \Ext^1(\ZZ(0),T(E))
$$
and similarly for more general bases that $\Spec(\QQ)$.

The case $E=\Gm$ is particularly interesting: for every smooth scheme $S$ over $\Spec(\ZZ)$, we want, in the category of motives with integer coefficients over $S$,
$$
  \Gamma(S,\OO_S^\times) \simto \Ext^1(\ZZ(0),\ZZ(1)).
\startverb\tag{2.4.1}\stopverb
$$
:::

:::: {.rmenv #chunk-2.5 title="2.5" latex="{2.5}"}
Let $M$ be a realisation system \ref{minus-three-points-1.9}.
We spell out what a realisation system $E$ given by an extension of $\QQ(0)$ by $M$ is, when $M$ is of weight $\leqslant-1$ (i.e. $M=W_{-1}(M)$).

::: {.trmenv #M1P title="(M1)P" latex="{(M1)P}"}
$E_\BB$ is an extension $M_\BB\to E_\BB\xrightarrow{u}\QQ$ of $\QQ$ by $M_\BB$.
Its data is equivalent to that of $P_\BB\coloneqq u^{-1}(1)$, endowed with its structure as a torsor (principal homogeneous space) for $M_\BB$, i.e. $m\in M_\BB$ acts on $P_\BB$ via $p\mapsto p+m$.
:::

::: {.trmenv #M234P title="(M2,3,4)P" latex="{(M2,3,4)P}"}
Similarly, the data of $E_\DR$ (resp. $E_\AAf$, $E_\crisp$) is equivalent to that of a torsor $P_\DR$ (resp. $P_\AAf$, $P_\crisp$) for $M_\DR$ (resp. $M_\AAf$, $M_\crisp$).
:::

::: {.trmenv #M5P title="(M5)P" latex="{(M5)P}"}
The comparison morphisms for $E$ can be identified with comparison morphisms $P_\BB\otimes\CC\simto P_\DR\otimes\CC$, $P_\BB\otimes\AAf\simto P_\AAf$, and $P_\DR\otimes\QQ_p\simto P_\crisp$ that are compatible with the analogous morphisms for $M$.
*Notation:* $\otimes$, see \ref{minus-three-points-0.4}.
:::

::: {.trmenv #M6P title="(M6)P" latex="{(M6)P}"}
Since $M$ is, by hypothesis, of weight $\leqslant-1$, and $\QQ(0)$ is of pure weight $0$, the weight filtration of $E$ is determined by that of $M$, i.e. $W_0(E)=E$, and $W_i(E)=W_i(E)$ for $i<0$.
:::

::: {.trmenv #M7P title="(M7)P" latex="{(M7)P}"}
\oldpage{108}The data of $F_\infty$ for $E$ is equivalent to that of an involution of $P_\BB$ that is compatible with that of $M_\BB$.
Axiom [(AM2)](minus-three-points-am2) for $E$ is that this involution is induced by the $\CC$-antilinear involution of $P_{\BB,\CC}=\PP_{\DR,\CC}$ with fixed points $P_{\DR,\RR}$.
:::

::: {.trmenv #M8P title="(M8)P" latex="{(M8)P}"}
The data of the Hodge filtration of $E_\DR$ is equivalent to that of the intersection $F^0P_\DR$ of $F^0E_\DR$ over $P_\DR$, which is a torsor for $F^0M_\DR$: for $p>0$, $F^pE_\DR=F^pM_\DR$; for $p=0$, $F^0E_\DR$ is generated by $F^0P_\DR$; and for $p<0$, $F^pE_\DR$ is the sum of $F^0E_\DR$ and $F^pM_\DR$.
In other words, the data [(M8)](minus-three-points-m8) for $E_\DR$ is that of a reduction of the structure group of $P_\DR$, from $M_\DR$ to $F^0M_\DR$.

The data of [(M1)](minus-three-points-m1), [(M2)](minus-three-points-m2), $\comp_{\DR/\BB}$, and [(M8)](minus-three-points-m8) are equivalent to the data of a torsor $F^0P_\DR$ for $F^0M_\DR$ and, in the $M_\DR\otimes\CC=M_\BB\otimes\CC$ torsor $P_{\DR,\CC}$ which is induced by $F^0M_\DR\to M_\DR\otimes\CC$, a $\QQ$-structure $P_\BB\subset P_{\DR,\CC}$ that is an $M_\BB$ torsor.
:::

::: {.trmenv #M9P title="(M9)P" latex="{(M9)P}"}
The data of the action of $\Gal(\bar{\QQ}/\QQ)$ on $E_\AAf$ is equivalent to that of an action of $\Gal(\bar{\QQ}/\QQ)$ on $P_\AAf$, which makes $P_\AAf$ an equivariant $M_\AAf$-torsor.
:::

::: {.trmenv #M10P title="(M10)P" latex="{(M10)P}"}
Similarly, the automorphism $\phi_p$ of $E_\DR\otimes\QQ_p$ corresponds to an automorphism $\phi_p$ of $P_\DR\otimes\QQ_p$ such that
$$
  \phi_p(x+m) = \phi_p(x) + \phi_p(m).
$$
:::

We leave to the reader the task of translating axioms [(AM1)](minus-three-points-am1) to [(AM5)](minus-three-points-am5) for $P$.
We note only that [(AM1)](minus-three-points-am1) and [(AM4)](minus-three-points-am4) follow from the same axioms for $M$, and that [(AM2)](minus-three-points-am2) and [(AM5)](minus-three-points-am5) can be expressed at best as functoriality in $\CC$, cf. \ref{minus-three-points-chunk-1.14}.
::::

::: {.rmenv #chunk-2.6 title="2.6 Definition" latex="{2.6 Definition}"}
—

i. A system of torsors, [(M1)P](#M1P) to [(M10)P](#M10P) in [(2.5)](#chunk-2.5), that satisfies the conditions required in order to define an extension $E$ of $\QQ(0)$ by a realisation system $M$ is called a *torsor in realisation systems*.

ii. If $M$ is a motive, then the torsor $P$ for $M$ is *motivic* (or a *torsor in motives*) if the extension $E$ is a motive.
:::

:::: {.rmenv #chunk-2.7 title="2.7" latex="{2.7}"}
Let $M$ be a realisation system with integer coefficients.
An *extension* $E$ of $\ZZ(0)$ by $M$ is an extension $E\otimes\QQ$ of $\QQ(0)$ by $M\otimes\QQ$, endowed with an integer structure such that the sequence $0\to M_\BB\to E_\BB\to\ZZ\to0$ is exact.

As in [(2.5)](#chunk-2.5), such an extension is described by a system of torsors.
\oldpage{109}As in [(1.24)](#chunk-1.24) and [(1.25)](#chunk-1.25), this corresponds to modifying [(2.5)](#chunk-2.5) as follows:

::: {.trmenv #M1PZ title="(M1)PZ" latex="{(M1)P$\ZZ$}"}
$P_\BB$ is an $M_\BB$-torsor.
:::

::: {.trmenv #M3t9PZ title="(M3,9)PZ" latex="{(M3,9)P$\ZZ$}"}
$P_\ell$ is, for each $\ell$, a $\Gal(\bar{\QQ}/\QQ)$-equivariant $M_\ell$-torsor.
It is equivalent to give a projective system of equivariant $M_{\ZZ/(n)}$-torsors $P_{\ZZ/(n)}$, or their projective limit $P_{\hZZ}$, which is an equivariant $M_{\hZZ}$-torsor.
:::

::: {.trmenv #M5PZ title="(M5)PZ" latex="{(M5)P$\ZZ$}"}
Replace $\comp_{\AAf,\BB}$ by $\comp_{\ell,\BB}$ for each $\ell$, or $\comp_{\ZZ/(n),\BB}$, or $\comp_{\hZZ,\BB}$.
:::

Such a system of torsors, which defines an extension of $\ZZ(0)$ by $M$, is also called a *torsor for $M$*.
It is said to be *motivic* if the corresponding extension is, i.e. if the torsor for $M\otimes\QQ$ that it defines is motivic.
::::

:::: {.rmenv #chunk-2.8 title="2.8" latex="{2.8}"}
We leave to the reader the task of understanding the constructions with bases $S$ more general than $\Spec(\QQ)$.
We note only that, in the de Rham realisation, $P_\DR$ is an $M_\DR$-torsor on $S_\QQ$.
It is endowed with a restriction of the structure group $F^0P_\DR\subset P_\DR$ to $F^0M_\DR$.
It is also endowed with an integrable connection $\nabla$.
Along each section $p$ of $P_\DR$, the vertical tangent space can be identified with $M_\DR$;
the connection $\nabla$ is thus a morphism
$$
  \nabla\colon P_\DR\to\Omega^1\otimes M_\DR.
$$
It satisfies $\nabla(p+m)=\nabla p+\nabla m$.
Transversality becomes the following:

::: {.trmenv #chunk-2.8.1 title="2.8.1" latex="{2.8.1}"}
For a local section $p$ of $F^0P_\DR$, $\nabla p\in\Omega^1\otimes F^{-1}(M_\DR)$.
:::
::::

::: {.rmenv #chunk-2.9 title="2.9" latex="{2.9}"}
We explicitly describe the torsor in motives $K(x)$ for $\ZZ(1)$ (the *Kummer torsor*) corresponding to $x\in\QQ^\times$ as in [(2.4.1)](#chunk-2.4.1).

The $\ZZ(1)_\BB$-torsor $K(x)_\BB$ is the torsor for $2\pi i\ZZ$ of logarithms of $x$.
Since $F^0\ZZ(1)_\DR=0$, we have $K(x)_\DR=\ZZ(1)_\DR=\QQ$.
The $\ZZ/(n)(1)$-torsor $K(x)_{\ZZ/(n)}$ is the torsor of $n$-th roots of unity of $x$.
The transition morphisms $K(x)/_{\ZZ(nm)}\to K(x)_{\ZZ/(n)}$ are given by $y\mapsto y^m$.
The Galois action is evident.

The morphism $\comp_{\DR,\BB}$ is induced by the inclusion of $K(x)_\BB$ into $\CC$.
The morphism $\comp_{\ZZ/(n),\BB}$ is induced by $K(x)_\BB\to K(x)_{\ZZ/(n)}$ given by $z\mapsto\exp(z/n)$.

The crystalline Frobenius $\phi_p\colon K(x)_\DR\otimes\QQ_p\to K(x)_\DR\otimes\QQ_p$, i.e. $\QQ_p\to\QQ_p$, is defined for $x$ a unit at $p$.
We denote by $\log$ the $p$-adic logarithm, which is characterised by
$$
  \phi_p^{-1}(0) = \log(x^{1-p}).
$$
:::

::: {.rmenv #chunk-2.10 title="2.10" latex="{2.10}"}
\oldpage{110}On $\Gm=\Spec\ZZ[q,q^{-1}]$, the universal section $q$ of $\Gm$ also defines a torsor in motives $K(q)$ for $\ZZ(1)$, on the base $\Gm$.
We now describe it.

The $\ZZ(1)_\BB$-torsor $K(q)_\BB$ on $C^\times$ is the local system of logarithms of $q$.
Since $F^0\ZZ(1)_\DR=0$, $K(q)_\DR$ is trivial: $K(n)_\DR=\OO$ (on ${\Gm}_\QQ$).
It is endowed with the integrable connection $\nabla\colon K(q)_\DR\to\Omega^1\otimes\ZZ(1)_\DR=\Omega^1$ given by
$$
  \nabla u = \dd u - \frac{\dd q}{q}.
$$
The $\ZZ/(n)(1)$-torsor $K(q)_{\ZZ/(n)}$ is that of the $n$-th roots of $q$.
This is a locally constant sheaf on $(\Gm\otimes\ZZ[1/n])_\et$.
Transition and comparison morphisms are defined as in [(2.9)](#chunk-2.9).

We now explain what the $F$-crystal structure is at $p$.
Let $\hGm$ be the completion of $\Gm$ along its fibre of characteristic $p$, and $\hGm\otimes\QQ_p$ the corresponding rigid analytic space.
For a Frobenius lifting $\widetilde{F}\colon\hGm\to\hGm$, the crystalline Frobenius is a morphism $\phi_p[\widetilde{F}]$, over $\hGm\otimes\QQ_p$, from $\widetilde{F}^\bullet K(q)_\DR$ to $K(q)_\DR$ that is horizontal and compatible with the torsor structures.
If we change $\widetilde{F}$ to $\widetilde{F}'$, then $\widetilde{F}$ and $\widetilde{F}'$ have the same reduction modulo $p$, the connection $\nabla$ gives an isomorphism of $\widetilde{F}^\bullet K(q)_\DR$ with $\widetilde{F}'^{\bullet} K(q)_\DR$, and the diagram
$$
  \begin{CD}
    \widetilde{F}^\bullet K(q)_\DR @>{\phi_p[\widetilde{F}]}>> K(q)_\DR
  \\@| @|
  \\\widetilde{F}'^{\bullet} K(q)_\DR @>>{\phi_p[\widetilde{F}']}> K(q)_\DR
  \end{CD}
$$
commutes.

In terms of $\phi_p^{-1}\colon K(q)_\DR\to\widetilde{F}'^{\bullet} K(q)_\DR$, and via the identifications $K(q)_\DR=\ZZ(1)_\DR=\OO$, whence $\widetilde{F}'^{\bullet}=\OO$, the compatibility with the torsor structures and with the connections can be written as
$$
  \begin{aligned}
    \phi_p^{-1}(k+m)
    &= \phi_p^{-1}(k) + pm
  \\\dd\phi_p^{-1}(0)
    &= \widetilde{F}^\bullet\left(\frac{\dd q}{q}\right) - p\frac{\dd q}{q}.
  \end{aligned}
$$
When we change the Frobenius lifting, we have
$$
  \phi_p^{-1}[\widetilde{F}'](0) - \phi_p^{-1}[\widetilde{F}](0)
  = \log(\widetilde{F}'/\widetilde{F}).
$$
For $\widetilde{F}\colon q\mapsto q^p$, we have
$$
  \phi_p^{-1}[q\mapsto q^p](0) = 0.
$$
\oldpage{111}For $x\in\QQ$ a unit at $p$, and $\widetilde{F}$ such that $\widetilde{F}(x)=x$, we thus have $\phi_p^{-1}[\widetilde{F}](0)=\log(x/x^p)$ at $x$, as required by [(2.9)](#chunk-2.9)
:::



# Torsors for $\ZZ(n)$ {#section-3}

\oldpage{112}The study of the fundamental group of $\PP^1\setminus\{0,1,\infty\}$ reveals, for each $k\geqslant2$, a torsor $P_{1,k}$ for $\ZZ(k)$ on $\Spec(\ZZ)$.
We will describe these torsors in this section.
The relation with $\pi_1$ will be explained in [§16](#section-16) (see [(16.23)](#chunk-16.23)) and the calculations to justify this will be given in [§19](#section-19).
We will then describe the torsors $P_{d,k}$ for $\ZZ(k)$ on $\Spec(\QQ(\sqrt[d]{1}))$, given by an analogous construction [(16.28)](#chunk-16.28).

The sum of the $\P_{d,k}$ and of $(-1)^k$ times its symmetry under $\zeta\mapsto\zeta^{-1}$ is torsion.
This is essentially equivalent to the adelic integral formulas for the value of the Dirichlet $L$ functions at negative integers: [(3.6)](#chunk-3.6), [(3.8)](#chunk-3.8), [(3.9)](#chunk-3.9), and [(3.14)](#chunk-3.14).
A geometric interpretation, which allows us to reprove these formulas, will be given in [§18](#section-18).

A geometric interpretation of the relations of distributions [(3.13)](#chunk-3.13) will be given in [§17](#section-17).

::: {.rmenv #chunk-3.1 title="3.1" latex="{3.1}"}
We denote by $P$ the torsor $P_{1,k}$ that we are going to define.
At the same time, we will define a trivialisation $u_\BB\in P_\BB$ of its Betti realisation.
Since $F^0\ZZ(k)_\DR=0$, we necessarily have that $P_\DR=\ZZ(k)_\DR=\QQ$.
The Betti structure is
$$
  \begin{aligned}
    P_\BB
    &= u_\BB + (2\pi i)^k\ZZ \subset \PP_{\DR,\CC} = \CC
    \quad\text{with}
  \\u_\BB
    &= -(k-1)!\zeta(k)
  \end{aligned}
\startverb\tag{3.1.1k}\stopverb
$$
where $\zeta$ is the Riemann $\zeta$ function.

Let $N$ be an integer; we will describe $P_{\ZZ/(N)}$.
For $z\in\CC$ with $z\neq1$, let $T_N(z)\coloneqq K(1-z)_{\ZZ/(N)}$ be the $\ZZ/N(1)$-torsor of $N$-th roots of $1-z$.
For $z=1$, we set $T_N(1)=K(1/N)_{\ZZ/(N)}$.
This convention ensures that the sum of the $T_N(\alpha)$ for $\alpha^N=1$ is trivialised: we have
$$
  \frac{1}{N}\prod(1-\alpha)
  = 1.
$$

Let $\alpha$ be an $N$-th root of $1$.
It defines $\alpha\colon\ZZ/N\to\ZZ/N(1)$ by $a\mapsto a\cdot\alpha$.
We thus obtain $\alpha^{\otimes(k-1)}\colon\ZZ/N(1)\to\ZZ/N(k)$.
Note that, for $\alpha=1$, this is the zero map.
We denote by $\alpha^{\otimes(k-1)}T(\alpha)$ the $\ZZ/N(k)$-torsor induced from $T(\alpha)$ by applying $\alpha^{\otimes(k-1)}$.
We have
$$
  P_{\ZZ/(N)}
  \coloneqq \sum_{\alpha^N=1} \alpha^{\otimes(k-1)}T_N(\alpha).
\startverb\tag{3.1.2k}\stopverb
$$
\oldpage{113}It is equivalent to sum over the $\alpha\neq1$.
This definition still makes sense in any algebraic closure $\overline{k}$ of $\QQ$, and the action of $\Gal(\bar{\QQ}/\QQ)$ is given by transport of structure.

We now define the transition morphisms $P_{\ZZ/(NM)}\to P_{\ZZ/(N)}$.
We have
$$
  \prod_{u^M=z} (1-u)
  = 1-z
\startverb\tag{3.1.3}\stopverb
$$
whence, for $z\neq0,1$, we obtain an isomorphism
$$
  T_N(z)
  = \prod_{u^M=z} T_N(u).
\startverb\tag{3.1.4}\stopverb
$$
If $\beta^N=1$ and $\alpha^M=\beta$, then the reduction $\mod N$ of $\alpha\colon\ZZ/NM\to\ZZ/NM(1)$ is $\beta\colon\ZZ/N\to\ZZ/N(1)$, and that of $T_{NM}(\alpha)$ is $T_N(\alpha)$.
From this, we obtain an isomorphism
$$
  \begin{aligned}
    P_{\ZZ/(NM)}\mod N
    &= \sum_{\beta^N=1} \sum_{\alpha^M=\beta} \alpha^{\otimes(k-1)}T_{NM}(\alpha) \mod N
  \\&= \sum_{\beta^N=1} \beta^{\otimes(k-1)} \sum_{\alpha^M=\beta} T_N(\alpha)
  \\&= \sum_{\beta^N=1} \beta^{\otimes(k-1)} T_N(\beta)
  \\&= P_{\ZZ/(N)}.
  \end{aligned}
$$
This defines the desired transition morphism.

For non-real negative $z$, we define the *principal determination* of $z\mapsto z^{1/N}$, and denote by $z^{1/N}$, that which takes the value of $1$ at $1$.
The morphism of torsors $\comp_{\ZZ/(N),\BB}$ sends $u_\BB$ to the point $u$ of $P_{\ZZ/(N)}$ defined by the $(1-\alpha)^{1/N}\in T(\alpha)$:
$$
  u_\BB
  \mapsto u
  = \sum \alpha^{\otimes(k-1)} ((1-\alpha)^{1/N}).
$$

If $z$ is not real and $\geqslant1$, then we have principal determinations
$$
  \prod_{u^M=z} (1-u)^{1/N}
  = (1-z)^{1/N}
\startverb\tag{3.1.5}\stopverb
$$
as we verify by analytic continuation from $z=0$, taking (3.1.3) into account.
It follows from (3.1.5) that the $\comp_{\ZZ/(N),\BB}$ are compatible with the transition morphisms.
:::

::: {.rmenv #chunk-3.2 title="3.2" latex="{3.2}"}
\oldpage{114}Some preliminaries, before defining $\phi_p$.
The $k$-logarithm is defined for $|z|\leqslant1$ by
$$
  \ell_k(z)
  = \sum z^n/n^k.
\startverb\tag{3.2.1}\stopverb
$$
The $\zeta(k)$ in the formula giving $P_\BB$ appears in our approach as the value at $1$ of $\ell_k$.
Let $p$ be a prime number and consider the formal series
$$
  \ell_k^{(p)}
  = \sum_{p\nmid n} z^n/n^k.
\startverb\tag{3.2.2}\stopverb
$$
This is the Taylor series expansion of a rigid analytic function on the projective line over $\QQ_p$ with the open disc of radius $1$ centred at $1$ removed.
Indeed, we have
$$
  \ell_k^{(p)}(z)
  = \lim_N \frac{1}{1-z^{p^N}} \sum_{n=1, p\nmid n}^{p^N-1} z^n/n^k.
\startverb\tag{3.2.3}\stopverb
$$
From (3.2.3) we get the identity
$$
  \ell_k^{(p)}(1/z)
  = -(-1)^k\ell_k^{(p)}(z).
\startverb\tag{3.2.4}\stopverb
$$

A formal series calculation gives, for $(N,p)=1$,
$$
  N^{k-1}\sum_{u^N=z} \ell_k^{(p)}(u)
  = \ell_k^{(p)}(z).
\startverb\tag{3.2.5}\stopverb
$$
This leads us to define the "principal value" at $1$
$$
  \vp\ell_k^{(p)}(1)
  \coloneqq \frac{N^{k-1}}{1-N^{k-1}} \sum_{\alpha^N=1,\alpha\neq1} \ell_k^{(p)}(\alpha).
\startverb\tag{3.2.6}\stopverb
$$
This number is independent of the choice of $N$ coprime to $p$.
By (3.2.4), it is zero for $k$ even.

With this notation, the crystalline Frobenius $\phi_p$ is given by
$$
  \phi_p^{-1}(0)
  = (k-1)!p^k\cdot\vp\ell_k^{(p)}(1).
\startverb\tag{3.2.7k}\stopverb
$$
:::

::: {.rmenv #chunk-3.3 title="Remark 3.3" latex="{Remark 3.3}"}
\oldpage{115}We have described the $\ZZ/(N)(k)$-torsor $P_{\ZZ/(N)}$ as a sum of torsors indexed by the $N$-th roots of $1$.
If $N$ is a power of a prime number $\ell$, say $N=\ell^n$, then we can again, thanks to (3.1.4), write it as a sum indexed by the set $\mu(N)^\times$ of primitive $N$-th roots of $1$.
Indeed, we have isomorphisms
$$
  \begin{aligned}
    P_{\ZZ/(N)}
    &= \sum_{\alpha^N=1}\ldots
  \\&= \sum_{a=1}^n \sum_{\mu(\ell^a)^\times} \ldots
  \\&= \sum_{a=1}^n \sum_{\alpha\in\mu(\ell^a)^\times}\alpha^{\otimes(k-1)} \sum_{\beta^{\ell^{n-a}}=\alpha} T_N(\beta).
  \end{aligned}
$$
In this sum, $\beta$ runs over, for each $a$, all the primitive $N$-th roots of $1$, whence
$$
  \begin{aligned}
    P_{\ZZ/(N)}
    &= \sum_{\beta\in\mu(N)^\times}\beta^{\otimes(k-1)}T_N(\beta) \cdot \sum_{a=1}^n\ell^{(n-a)(k-1)}
  \\&= \frac{1}{1-\ell^{k-1}} \sum_{\beta\in\mu(N)^\times}\beta^{\otimes(k-1)}T_N(\beta).
  \end{aligned}
$$
The cohomology class of $P_{\ZZ/(N)}$ (for $N=\ell^n$) in $\HH^1(\Spec(\QQ),\ZZ/(N)(k))$ thus admits the following description.
Let $\QQ(\zeta)$ be the cyclotomic field generated by a primitive $N$-th root of $1$.
In $\HH^1(\Spec(\QQ(\zeta)),\ZZ/N(1))$, let $\delta(1-\zeta)$ be the Kummer coboundary of $1-\zeta$.
On $\Spec(\QQ(\zeta))$, $\zeta$ identifies the $\ZZ/N(a)$ with one another, and we can think of $\delta(1-\zeta)$ as a class with values in $\ZZ/N(k)$.
More precisely, we consider $\zeta^{\otimes(k-1)}\cup\partial(1-\zeta)\in\HH^1(\Spec(\QQ(\zeta)),\ZZ/N(k))$.
We have
$$
  \cl(P_{\ZZ/\ell^n})
  = \frac{1}{1-\ell^{k-1}} \Tr_{\QQ(\zeta)/\QQ}(\zeta^{\otimes(k-1)}\cup\partial(1-\zeta))
$$
and the class of $P_\ell$ is the limit of these classes.
:::

::: {.rmenv #chunk-3.4 title="Remark 3.4" latex="{Remark 3.4}"}
We denote by $\zeta^{(p)}(s)$ the $\zeta$ function with its Eulerian factor at $p$ removed:
$$
  \zeta^{(p)}(s)
  \coloneqq \sum_{p\nmid n} 1/n^s.
$$
We know that the values of $\zeta^{(p)}(s)$ on the negative integers are rational and admit a $p$-adic interpolation.
More precisely,

a. Let $\CC_p$ be the completion of an algebraic closure of $\QQ_p$.
  Then the characters $\chi\colon\ZZ_p^\times\to\CC_p^\times$ are the points of a rigid analytic space.

b. \oldpage{116}There exists exactly one rigid analytic function $\zeta_p^{(p)}(\chi)$, with a simple pole at $\chi=(x\mapsto x^{-1})$, such that
  $$
    \zeta_p^{(p)}(x\mapsto x^{-1})
    = \zeta^{(p)}(n)\in\QQ
  $$
  for every integer $n<0$.

We set, for $n\in\ZZ$ with $n\neq1$,
$$
  \zeta_p^{(p)}(n)
  \coloneqq \zeta_p^{(p)}(x\mapsto x^{-1}).
$$
This notation differs from that of [@C] or [@Ko]: our $\zeta_p^{(p)}$ is not a continuous $p$-adic function of the *integer* $n$.
Instead, it is a continuous function of the *character* $x\mapsto x^n$, itself a continuous function of $n$ if and only if we restrict $n$ to an arithmetic progression of difference $p-1$.
We have
$$
  \zeta_p^{(p)}(n)
  = \lim_a \zeta^{(p)}(n-(p-1)p^a).
$$
The trivial zeros of $\zeta$ force $\zeta_p^{(p)}(n)=0$ for even $n$, i.e. for $x\mapsto x^{-n}$ an even character.
More generally, $\zeta_p^{(p)}(\chi)=0$ for even $\chi$.

With this notation, we have (cf. [@C; @Ko])
$$
  \vp \ell_k^{(p)}(1)
  = \zeta_p^{(p)}(k)
$$
and (3.2.7) can be rewritten as
$$
  \phi_p^{-1}(0)
  = (k-1)! p^k\zeta_p^{(p)}(k).
\startverb\tag{3.4.1k}\stopverb
$$
:::

::: {.itenv #chunk-3.5 title="Proposition 3.5" latex="{Proposition 3.5}"}
For $k$ even, the torsor $P_{1,k}$ is torsion, with order equal to the denominator of $\frac{1}{2}\zeta(1-k)$.
:::

::: {.rmenv #chunk-3.6 title="Paraphrasing 3.6" latex="{Paraphrasing 3.6}"}
Let $P$ be a torsor for a realisation system $M$ with integer coefficients.
The fact that $P$ is $n$-torsion means more than "every realisation is $n$-torsion".
Let $\frac{1}{n}M$ be the realisation system $M\otimes\QQ$, endowed with the integer structure $\frac{1}{n}M_\BB$.
It is isomorphic to $M$, by an isomorphism that sends $M\hookrightarrow\frac{1}{n}M$ by $n\colon M\to M$.
The fact that $P$ is $n$-torsion thus implies that it becomes trivial under $M\to\frac{1}{2}M$.
For $M$ of weight $\leqslant-1$, this implies:

a. \oldpage{117}$P_\BB+\frac{1}{n}M_\BB\cap F^0 P_\DR\otimes\CC\neq\phi$ (the intersection in $P_\BB\otimes\CC\simto P_\DR\otimes\CC$).
  The point of intersection $x$ is then unique, since $M_\BB\cap F^0(M_\DR)\otimes\CC=0$.
b. $x\in F^0 P_{DR}$, i.e. is defined over $\QQ$ for the $\QQ$-structure $\DR$.
c. The image of $x$ under $\comp_{\AAf,B}$ is fixed by Galois.
d. The image of $x$ under $\comp_{\crisp,\DR}$ is fixed by $\phi_p$.

Suppose that $F^0 M_\DR=0$.
Then $P_\DR=M_\DR$, and we can identify $P_\BB$ with a lateral class of $M_\BB\subset M_\DR\otimes\CC$.
Condition (a) then becomes $P_\BB\subset\frac{1}{n}M_\BB$.
We have $x=0$, and (b) is automatic.
We can write (d) as $\phi_p(0)=0$.
Let $p\in P_\BB$.
Denote by $p_M$ its image in $\frac{1}{n}M_\BB$, and set $p^\wedge=\comp_{\hZZ,\BB}(p)\in P_{\hZZ}$ and $(p_M)^\wedge=\comp_{\AAf,\BB}(p_M)\in M_\AAf$.
Condition (c) can then be written as
$$
  \sigma p^\wedge - p^\wedge
  = (\sigma-1)(p_M)^\wedge.
\startverb\tag{3.6.1}\stopverb
$$

Let $M=\ZZ(k)$ with $k\geqslant1$.
Let $\sigma\in\Gal(\bar{\QQ}/\QQ)$ with image $c$ in $\hZZ^\times$, i.e. $\sigma(\zeta)=\zeta^c$ for $\zeta$ a root of unity.
Condition (3.6.1) can then be written as
$$
  \sigma p^\wedge - p^\wedge
  = (c^k-1)(p_M)^\wedge.
\startverb\tag{3.6.2}\stopverb
$$
Modulo $N$, we obtain: let $c$ be an integer coprime to $Nn$, with $\sigma$ inducing $\zeta\mapsto\zeta^c$ on the $(Nn)$-th roots of unity.
Then $(c^k-1)p_M\in M_\BB$, and
$$
  \comp_{\hZZ,\BB}((c^k-1)p_M)
  \equiv \sigma p^\wedge - p^\wedge \mod{N}.
\startverb\tag{3.6.3}\stopverb
$$

In [(3.5)](#chunk-3.5), $k$ is even, and we can take $p=-(k-1)!\zeta(k)$, and (3.6.3) is a Galois formula for $-(c^k-1)(k-1)!\zeta(k)$ modulo $N(2\pi i)^k\ZZ$.
We recover a known formula expressing $\zeta$ on the negative integers as an adelic integral.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
The above description shows that, if $P$ is of finite order, then its order can be read from its Hodge realisation.
:::

::: {.rmenv #chunk-3.7 title="3.7 (Proof of 3.5)" latex="{3.7 (Proof of 3.5)}"}
Let
:::
